In [1]:
import cv2
import numpy as np

### 图片加法


In [14]:
cat = cv2.imread('cat.jpeg')
dog = cv2.imread('dog.png')

print(cat.shape, dog.shape)


(480, 640, 3) (500, 667, 3)


In [15]:
# 从狗里面切出猫的大小
dog = dog[0:480,0:640,:]
cv2.imshow('dog', dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
cat_and_dog = cv2.add(cat, dog)
# add: 按位置相加，超过255就取255
cv2.imshow('cat_and_dog', cat_and_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# 图片可以对单个数字运算,超出255会被截断，取余%255（减去255）
dog += 100
cv2.imshow('dog', dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 减法
剪完后小于0，置于0

In [22]:
new_img = cv2.subtract(cat, dog)
cv2.imshow('subtract', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 乘法除法


In [24]:
new_img = cv2.multiply(cat, dog)
cv2.imshow('multiply', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

new_img = cv2.divide(cat, dog)
cv2.imshow('divide', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 图像的融合
不是简单的加法，而是线性的运算

+ cv2.addWeighted(src, alpha, sr2, beta, gamma)

new_img = img1 * w1 + img2 * w2 + bias

In [29]:
cat = cv2.imread('cat.jpeg')
dog = cv2.imread('dog.png')
dog = dog[0:480,0:640,:]
new_img = cv2.addWeighted(cat,0.3, dog,0.7, 10)
cv2.imshow('addWeighted', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 逻辑运算（与、非、异或、或）
对应位置运算

In [45]:
cat = cv2.imread('cat.jpeg')
dog = cv2.imread('dog.png')
dog = dog[0:480,0:640,:]

# 变成二进制再运算
print(204 & 213, 204 ^ 213)
print('注意：在opencv中，0取反是255，与python中不同', ~255)

# 非操作：相当于 255 - image
cat_not = cv2.bitwise_not(cat)
cv2.imshow('cat_not and cat', np.hstack((cat_not, cat)))
cv2.waitKey(0)
cv2.destroyAllWindows()

# 与操作：比较黑的留下来了
cat_and_dog = cv2.bitwise_and(cat, dog)
cv2.imshow('cat_and_dog', cat_and_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 异或操作，
cat_xor_dog = cv2.bitwise_xor(cat, dog)
cv2.imshow('cat_xor_dog', cat_xor_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 或操作：整体数字变大了，也就是变白了
cat_or_dog = cv2.bitwise_or(cat, dog)
cv2.imshow('cat_or_dog', cat_or_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

196 25
注意：在opencv中，0取反是255，与python中不同 -256


### 图像的放大与缩小
+ resize(src:要缩放的图片, dsize:缩放之后的图片大小，元组列表都可表示, dst:可选，缩放之后的输出图片，fx,fy:xy的缩放比，interpolation:插值算法)
    + INTER_NEAREST: 邻近插值
    + INTER_LINEAR: 双线性插值（原图4个点插值）,默认
    + INTER_CUBIC: 三次插值（原图16个值）
    + INTER_AREA: 区域插值，效果最好，时间最长

In [65]:
cat = cv2.imread('cat.jpeg')
dog = cv2.imread('dog.png')
print('行与列：',cat.shape, dog.shape,'对应图片的高度与宽度')
new_cat = cv2.resize(cat, dsize=(667, 500), interpolation=cv2.INTER_NEAREST)
cv2.imshow('resize and dog', np.hstack((new_cat, dog)))
cv2.waitKey(0)
cv2.destroyAllWindows()

行与列： (480, 640, 3) (500, 667, 3) 对应图片的高度与宽度


In [70]:
# 按照xy轴缩放,dst=None, 并且fx,fy要写名称参数
new_dog = cv2.resize(dog, dsize=None, fx=0.5, fy=0.1)
cv2.imshow('resize and dog', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 添加自己的小logo

In [79]:
logo = np.zeros((200,200,3),dtype=np.uint8)
logo[20:120,20:120]=[0,0,255]
logo[80:180,80:180]=[0,255,0]
# cv2.imshow('logo', logo)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# 利用掩码
mask = np.zeros((200,200), dtype=np.uint8)
# 白色与任何东西与都是白色
mask[20:120,20:120]=255
mask[80:180,80:180]=255
m = cv2.bitwise_not(mask)

# 浅拷贝
roi = dog[0:200, 0:200]
# 自己与roi自己还是自己，结果再mask，如果与的结果是True返回原图的像素，否则返回0
tmp = cv2.bitwise_and(roi, roi, mask=m)
# cv2.imshow('tmp', tmp)

dst = cv2.add(tmp, logo)
# cv2.imshow('dst', dst)
# 在dog上还原
dog[0:200, 0:200] =dst
cv2.imshow('logo dog', dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 图像的翻转
+ cv2.flip(src, flipCode)
    + flipCode=0:上下翻转
    + flipCode>0:左右翻转
    + flip<0: 上下左右翻转

In [80]:
dog = cv2.imread('dog.png')
new_dog = cv2.flip(dog, flipCode=0)
cv2.imshow('flipCode=0 up down', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 图像的旋转
+ cv2.rotate(img, rotateCode)
    + ROTATE_90_CLOCKWISE：顺时针90度
    + ROTATE_180
    + ROTATE_90_COUNTERCLOCKWISE:逆时针90度

In [81]:
dog = cv2.imread('dog.png')
new_dog = cv2.rotate(dog, rotateCode=cv2.ROTATE_90_CLOCKWISE)
cv2.imshow('ROTATE_90_CLOCKWISE', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 仿射变换
旋转、缩放、平移
之平移
+ cv2.warpAffine(src,M,dsize,flags,mode,value)
    +  M 变换矩阵
    + flag：与resize的插值一致
    + mode：边界外推法标志
    + value：填充边界值

平移矩阵
![平移矩阵](平移矩阵.png)

（下面的1无所谓，只是为了成为1×1的矩阵）

In [89]:
dog = cv2.imread('dog.png')
h, w, ch = dog.shape

# tx=100往右边移动200个元素
# 注意M 不需要与img同shape
M = np.float32([[1, 0, 200], [0, 1, 0]])
# opencv中先w，再w
new = cv2.warpAffine(dog, M, (w,h))
cv2.imshow('new', new)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 获取opencv提供的变换矩阵

+ cv2.getRotationMatrix2D(center,angle,scale)

In [96]:
dog = cv2.imread('dog.png')
h, w, ch = dog.shape

M = cv2.getRotationMatrix2D((100,100),45,0.5)
new = cv2.warpAffine(dog, M, (w,h))
cv2.imshow('new', new)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 以图像中心旋转
M = cv2.getRotationMatrix2D((w/2,h/2),45,.5)
new = cv2.warpAffine(dog, M, (w,h))
cv2.imshow('new', new)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(M)
print(new.shape, M.shape)

[[  0.35355339   0.35355339 127.20159659]
 [ -0.35355339   0.35355339 279.52170811]]
(500, 667, 3) (2, 3)


### 通过三个点确定变换矩阵

In [107]:

dog = cv2.imread('dog.png')
h, w, ch = dog.shape
# 需要原始图片三个点坐标和变换之后三个对应的坐标
src = np.float32([[250,100],[100,50],[200,100]])
dst = np.float32([[100,150],[360,100],[280,100]])
M = cv2.getAffineTransform(src,dst)
new = cv2.warpAffine(dog, M, (w,h))
cv2.imshow('new', new)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(M)
print(new.shape, M.shape)

[[ -3.6   5.6 440. ]
 [  1.   -2.  100. ]]
(500, 667, 3) (2, 3)


### 透视变换
透视变换就是把一种坐标系变换成另一种坐标系。简单说就是把一张斜的图变正

+ warpPerspective(img,M,dsize)
+ 对于透视变换来说，M是一个3 $\times$ 3的矩阵
+ getPerspectiveTransform(src,dst)获取透视变换的矩阵，需要4个点即图片的4个角

In [166]:
img = cv2.imread('123.png')


h, w, ch = img.shape
print(h, w, ch)
# 利用画图软件获取透视变化顶点坐标，这里按照的左上->右上->左下->右下
src = np.float32([[79,250], [381,124],[199,468], [509,274]])
# # src 是原图的4个点坐标
# src = np.float32([[0,0], [0,w],[0,h], [w,h]])
dst = np.float32([[0,0], [0,200], [0,300], [200,300]])
M = cv2.getPerspectiveTransform(src=src,dst=dst)
print(type(M), M.dtype, M.shape, M)

# warp变换 Affine 仿射

# img = cv2.warpAffine(img,M,dsize=(509,274))不要用错，透视不是这一个
new = cv2.warpPerspective(img, M, dsize=(w,h), flags=cv2.INTER_NEAREST)
cv2.imshow('img', img)
cv2.imshow('new', new)

cv2.waitKey(0)
cv2.destroyAllWindows()

598 534 3
<class 'numpy.ndarray'> float64 (3, 3) [[ 5.58383289e-17 -7.87574998e-17  1.79557496e-14]
 [ 3.89831512e-02 -6.98448126e-01  1.71532363e+02]
 [-3.22326552e-04 -3.05086053e-03  1.00000000e+00]]
